// @generated by protoc-gen-connect-es v0.10.0 with parameter "target=ts"
// @generated from file monitor.proto (package xmon, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListBlocksRequest, ListBlocksResponse, ListNodesRequest, ListNodesResponse, ListSlotsRequest, ListSlotsResponse } from "./monitor_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service xmon.Monitor
 */
export const Monitor = {
  typeName: "xmon.Monitor",
  methods: {
    /**
     * @generated from rpc xmon.Monitor.ListNodes
     */
    listNodes: {
      name: "ListNodes",
      I: ListNodesRequest,
      O: ListNodesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc xmon.Monitor.ListBlocks
     */
    listBlocks: {
      name: "ListBlocks",
      I: ListBlocksRequest,
      O: ListBlocksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc xmon.Monitor.ListSlots
     */
    listSlots: {
      name: "ListSlots",
      I: ListSlotsRequest,
      O: ListSlotsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

